### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by x0204** [brudfors/UniRes#24]
I am currently facing an error while attempting to execute UniRes within a Docker environment. Below are the details of the command used and the resulting error message:

Command:
docker run --runtime=nvidia --rm -v /home/chang/GBM_Data:/home/chang/GBM_Data unires:latest unires --common_output /home/chang/GBM_Data/GBM_original/20240618/For_Use/XXXX/Post/T2W_FLAIR.nii /home/chang/GBM_Data/GBM_original/20240618/For_Use/XXXX/Post/T2W.nii

Error message:
==========
== CUDA ==
==========

CUDA Version 11.3.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING:root:nitorch uses its non-compiled backend (TS). Some algorithms may be slow.

  _   _       _ ____           
 | | | |_ __ (_)  _ \ ___  ___ 
 | | | | '_ \| | |_) / _ \/ __|
 | |_| | | | | |  _ <  __/\__ \
  \___/|_| |_|_|_| \_\___||___/

18/07/2024 00:54:18 | GPU: NVIDIA GeForce RTX 4090, CUDA: True, PyTorch: 1.10.2+cu111

Input
c=0, n=0 | fname=/home/chang/GBM_Data/GBM_original/20240618/For_Use/5800011/Post/T2W_FLAIR.nii
c=1, n=0 | fname=/home/chang/GBM_Data/GBM_original/20240618/For_Use/5800011/Post/T2W.nii

Estimating model hyper-parameters... Traceback (most recent call last):
  File "/usr/local/bin/unires", line 11, in <module>
    load_entry_point('unires', 'console_scripts', 'unires')()
  File "/workspace/UniRes/unires/_cli.py", line 243, in run
    _preproc(**vars(args))
  File "/workspace/UniRes/unires/_cli.py", line 52, in _preproc
    dat_y, mat_y, pth_y = preproc(pth, s)
  File "/workspace/UniRes/unires/run.py", line 313, in preproc
    x, y, sett = init(data, sett)
  File "/workspace/UniRes/unires/run.py", line 253, in init
    x = _estimate_hyperpar(x, sett)
  File "/workspace/UniRes/unires/_core.py", line 125, in _estimate_hyperpar
    prm_noise, prm_not_noise = estimate_noise(
  File "/usr/local/lib/python3.8/dist-packages/nitorch/tools/img_statistics.py", line 196, in estimate_noise
    model.fit(x, W=dat, verbose=verbose, max_iter=max_iter,
  File "/usr/local/lib/python3.8/dist-packages/nitorch/vb/mixtures.py", line 104, in fit
    Z, lb = self._em(X, max_iter=max_iter, tol=tol, verbose=verbose, W=W)
  File "/usr/local/lib/python3.8/dist-packages/nitorch/vb/mixtures.py", line 162, in _em
    Z[:, k] = torch.log(self.mp[k]) + self._log_likelihood(X, k)
  File "/usr/local/lib/python3.8/dist-packages/nitorch/vb/mixtures.py", line 506, in _log_likelihood
    log_pdf = log_pdf + besseli(0, X * (nu / sig2), 'log')
  File "/usr/local/lib/python3.8/dist-packages/nitorch/core/math.py", line 1255, in besseli
    z = besseli0(z, code)
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_mul_pow_mul_a_11258522613074717678(double* tzm_1, double* aten_add_5) {
{
  double tzm_1_1 = __ldg(tzm_1 + (long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x));
  aten_add_5[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = ((tzm_1_1 * 0.2666666666666667) * (tzm_1_1 * 0.2666666666666667)) * (((tzm_1_1 * 0.2666666666666667) * (tzm_1_1 * 0.2666666666666667)) * (((tzm_1_1 * 0.2666666666666667) * (tzm_1_1 * 0.2666666666666667)) * (((tzm_1_1 * 0.2666666666666667) * (tzm_1_1 * 0.2666666666666667)) * (((tzm_1_1 * 0.2666666666666667) * (tzm_1_1 * 0.2666666666666667)) * 0.0045813 + 0.0360768) + 0.2659732) + 1.2067492) + 3.0899424) + 3.5156229) + 1.0;
}
}
Any thought?
Could you please provide some insights into resolving this issue? Your assistance would be greatly appreciated.

**Comment by balbasty** [comment]
Hi @MarioPasc I'll try to fix nitorch so that it works with more recent pytorch. I'll keep you updated through this issue.

**Comment by balbasty** [comment]
@MarioPasc @brudfors 

nitorch now seems to work with pytorch 2. I've tested running UniRes with the most recent nitorch (compiled/uncompiled backend, cpu/gpu), and it worked. 

My GPU is an ampere series (8.6). I haven't gotten to test it on more recent architectures.

@brudfors I think we could bump the nitorch pin to the most recent commit, and maybe also use a more recent docker image (it's currently using cuda 10.1)?

**Comment by brudfors** [comment]
@MarioPasc @balbasty With UniRes 0.3 release this should be fixed, please look at the updated README on how to install.
